name: Playwright Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Run Playwright Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - name: Setup pnpm cache
        uses: actions/cache@v3
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install

      - name: Install Playwright browsers
        run: pnpm exec playwright install --with-deps

      - name: Create env file
        env:
          USERNAME_STANDARD: ${{ secrets.USERNAME_STANDARD }}
          PASSWORD_STANDARD: ${{ secrets.PASSWORD_STANDARD }}
          USERNAME_LOCKED_OUT: ${{ secrets.USERNAME_LOCKED_OUT }}
          PASSWORD_LOCKED_OUT: ${{ secrets.PASSWORD_LOCKED_OUT }}
          USERNAME_PROBLEM: ${{ secrets.USERNAME_PROBLEM }}
          PASSWORD_PROBLEM: ${{ secrets.PASSWORD_PROBLEM }}
          USERNAME_PERFORMANCE_GLITCH: ${{ secrets.USERNAME_PERFORMANCE_GLITCH }}
          PASSWORD_PERFORMANCE_GLITCH: ${{ secrets.PASSWORD_PERFORMANCE_GLITCH }}
          USERNAME_ERROR: ${{ secrets.USERNAME_ERROR }}
          PASSWORD_ERROR: ${{ secrets.PASSWORD_ERROR }}
          USERNAME_VISUAL: ${{ secrets.USERNAME_VISUAL }}
          PASSWORD_VISUAL: ${{ secrets.PASSWORD_VISUAL }}
          USERNAME_INVALID: ${{ secrets.USERNAME_INVALID }}
          PASSWORD_INVALID: ${{ secrets.PASSWORD_INVALID }}
          BASE_URL: ${{ secrets.BASE_URL }}
        run: |
          cat << EOF > .env
          USERNAME_STANDARD=${USERNAME_STANDARD}
          PASSWORD_STANDARD=${PASSWORD_STANDARD}
          USERNAME_LOCKED_OUT=${USERNAME_LOCKED_OUT}
          PASSWORD_LOCKED_OUT=${PASSWORD_LOCKED_OUT}
          USERNAME_PROBLEM=${USERNAME_PROBLEM}
          PASSWORD_PROBLEM=${PASSWORD_PROBLEM}
          USERNAME_PERFORMANCE_GLITCH=${USERNAME_PERFORMANCE_GLITCH}
          PASSWORD_PERFORMANCE_GLITCH=${PASSWORD_PERFORMANCE_GLITCH}
          USERNAME_ERROR=${USERNAME_ERROR}
          PASSWORD_ERROR=${PASSWORD_ERROR}
          USERNAME_VISUAL=${USERNAME_VISUAL}
          PASSWORD_VISUAL=${PASSWORD_VISUAL}
          USERNAME_INVALID=${USERNAME_INVALID}
          PASSWORD_INVALID=${PASSWORD_INVALID}
          BASE_URL=${BASE_URL}
          EOF

      - name: Debug secrets availability
        run: |
          if [ -n "${{ secrets.BASE_URL }}" ]; then
            echo "BASE_URL is set"
          else
            echo "BASE_URL is not set"
          fi

      - name: Run Playwright tests
        run: pnpm test
        env:
          CI: true

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: |
            playwright-report/
            test-results/
            allure-results/

      - name: Generate Allure Report
        if: always()
        run: |
          curl -o allure-2.24.1.tgz -OL https://repo.maven.apache.org/maven2/io/qameta/allure/allure-commandline/2.24.1/allure-commandline-2.24.1.tgz
          tar -zxvf allure-2.24.1.tgz -C /tmp
          /tmp/allure-2.24.1/bin/allure generate allure-results --clean -o allure-report

      - name: Upload Allure Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report/